(function(){
"use strict";
const catalog=window.CHILLER_CATALOG||[];
const SLOT_MS=30*60*1000;
const channels=[
["Hermit TV","Hermit-TV"],["Star Launcher","Star-Launcher"],["HBO","HBO"],["Cinemax","Cinemax"],["Showtime","Showtime"],["Starz","Starz"],["Encore","Encore"],["Cartoon Network","Cartoon-Network"],["WGN","WGN"],["NBC","NBC"],["FOX","FOX"],["PBS","PBS"],["TNT","TNT"],["History Channel","History-Channel"],["Disney Vintage","Disney"],["Discovery","Discovery"],["Chiller","Chiller"],["Trump TV","Trump-TV"],["ShopLC","ShopLC"],["StarQuest","TV-Database"],["Astraflix","Astraflix"],["Syncord","Syncord"],["Vintech","Vintech"],["Abstractia","Abstractia-"],["Flix Blender","Flix-Blender"],["Animasync","Animasync"]
].map(x=>({name:x[0],slug:x[1],url:"https://www-infinity4.github.io/"+x[1]+"/"}));
const $=id=>document.getElementById(id);
const els={clock:$("stationClock"),title:$("nowTitle"),meta:$("nowMeta"),time:$("programTime"),mode:$("modeLabel"),player:$("player"),enter:$("enterButton"),station:$("stationCard"),stationTitle:$("stationCardTitle"),stationCountdown:$("stationCardCountdown"),position:$("positionLabel"),remaining:$("remainingLabel"),bar:$("progressBar"),next:$("nextCards"),guide:$("guideRows"),guideDate:$("guideDate"),share:$("shareButton"),shareStatus:$("shareStatus"),walletAmount:$("walletAmount")};
let ytPlayer=null,playerReady=false,entered=false,mode="live",manualOffset=0,lastSlotKey="",errorTries=0,currentProgram=null;
function pad(n){return String(n).padStart(2,"0")}
function dateKey(d){return d.getFullYear()+"-"+pad(d.getMonth()+1)+"-"+pad(d.getDate())}
function dayStart(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function fmtTime(d){return d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}
function fmtDur(s){s=Math.max(0,Math.floor(s));const m=Math.floor(s/60),sec=s%60;return m+":"+pad(sec)}
function hash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=seed||123456789;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function shuffledForDay(d){const r=rng(hash("CHILLER|"+dateKey(d))),base=catalog.slice();for(let i=base.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[base[i],base[j]]=[base[j],base[i]]}const out=[];for(let i=0;i<48;i++){let p=base[(i+Math.floor(i/base.length)*3)%base.length];if(out.length&&out[out.length-1].id===p.id)p=base[(base.indexOf(p)+1)%base.length];out.push(p)}return out}
function stateAt(now=new Date()){
 const start=dayStart(now),elapsed=now-start,index=Math.max(0,Math.min(47,Math.floor(elapsed/SLOT_MS))),slots=shuffledForDay(now),program=slots[index],slotStart=new Date(start.getTime()+index*SLOT_MS),slotEnd=new Date(slotStart.getTime()+SLOT_MS),elapsedSec=(now-slotStart)/1000;
 return{start,index,slots,program,slotStart,slotEnd,elapsedSec,remainingSec:(slotEnd-now)/1000,inProgram:elapsedSec<program.runtimeSeconds,key:dateKey(now)+"-"+index};
}
function imageFor(p){return p.posterUrl||("https://i.ytimg.com/vi/"+p.videoId+"/hqdefault.jpg")}
function renderRemote(){const active="Chiller";const html=channels.map(c=>`<a${c.slug===active?' aria-current="page"':''} href="${c.url}">${c.name}</a>`).join("");$("channelNav").innerHTML=html;$("directoryNav").innerHTML=html}
function renderNext(st){els.next.innerHTML="";for(let n=1;n<=4;n++){const idx=(st.index+n)%48,p=st.slots[idx],time=new Date(st.start.getTime()+idx*SLOT_MS);const a=document.createElement("article");a.className="program-card";a.style.setProperty("--art",`url('${imageFor(p)}')`);a.innerHTML=`<time>${fmtTime(time)}</time><b>${p.title}</b><span>${p.series} · ${p.year} · ${p.rating}</span>`;els.next.appendChild(a)}}
function renderGuide(){els.guide.innerHTML="";const now=new Date();els.guideDate.textContent="Viewer-local schedule";for(let day=0;day<7;day++){const d=new Date(now.getFullYear(),now.getMonth(),now.getDate()+day),slots=shuffledForDay(d),start=dayStart(d),wrap=document.createElement("section");wrap.className="guide-day";const label=day===0?"Today":day===1?"Tomorrow":d.toLocaleDateString([],{weekday:"long",month:"short",day:"numeric"});wrap.innerHTML=`<h3>${label}</h3><div class="guide-slots"></div>`;const grid=wrap.querySelector(".guide-slots");slots.forEach((p,i)=>{const slot=document.createElement("div");slot.className="guide-slot"+(day===0&&i===stateAt(now).index?" now":"");slot.innerHTML=`<time>${fmtTime(new Date(start.getTime()+i*SLOT_MS))}</time><b>${p.title}</b>`;grid.appendChild(slot)});els.guide.appendChild(wrap)}}
function updateHeader(st){currentProgram=st.program;els.clock.textContent=fmtTime(new Date())+" local";els.title.textContent=st.program.title;els.meta.textContent=st.program.series+" · "+st.program.year+" · "+st.program.rating;els.time.textContent=fmtTime(st.slotStart)+"–"+fmtTime(st.slotEnd);const displayElapsed=mode==="live"?st.elapsedSec:manualOffset;els.position.textContent=mode==="live"?"Synced with the Chiller schedule":fmtDur(displayElapsed)+" from start";els.remaining.textContent=fmtDur(st.remainingSec)+" until next program";els.bar.style.width=Math.min(100,Math.max(0,st.elapsedSec/(SLOT_MS/1000)*100))+"%";document.body.style.setProperty("--current-art",`url('${imageFor(st.program)}')`)}
function showBreak(st){els.station.hidden=false;els.stationTitle.textContent="Next: "+st.slots[(st.index+1)%48].title;els.stationCountdown.textContent="Begins in "+fmtDur(st.remainingSec);if(ytPlayer&&playerReady){try{ytPlayer.stopVideo()}catch(_){}}}
function hideBreak(){els.station.hidden=true}
function createOrLoad(videoId,start){errorTries=0;if(!window.YT||!YT.Player){return}if(!ytPlayer){ytPlayer=new YT.Player("player",{videoId,playerVars:{autoplay:1,start:Math.max(0,Math.floor(start)),playsinline:1,rel:0,modestbranding:1,origin:location.origin},events:{onReady:e=>{playerReady=true;e.target.playVideo()},onError:onPlayerError}})}else if(playerReady){ytPlayer.loadVideoById({videoId,startSeconds:Math.max(0,Math.floor(start))})}}
function onPlayerError(){if(errorTries>=3){els.station.hidden=false;els.stationTitle.textContent="This source is unavailable right now";els.stationCountdown.textContent="The schedule will move to the next program automatically.";return}errorTries++;const idx=catalog.findIndex(x=>x.id===currentProgram.id),alt=catalog[(idx+errorTries)%catalog.length];els.title.textContent=alt.title+" · alternate feed";ytPlayer.loadVideoById({videoId:alt.videoId,startSeconds:0})}
function playLive(){const st=stateAt();mode="live";els.mode.textContent="LIVE CHILLER";if(!st.inProgram){showBreak(st);return}hideBreak();createOrLoad(st.program.videoId,st.elapsedSec)}
function playAt(seconds,label){const st=stateAt();mode="manual";manualOffset=Math.max(0,Math.min(seconds,st.program.runtimeSeconds-1));els.mode.textContent=label;hideBreak();createOrLoad(st.program.videoId,manualOffset)}
window.onYouTubeIframeAPIReady=function(){if(entered)playLive()};
els.enter.addEventListener("click",()=>{entered=true;els.enter.hidden=true;playLive()});
$("liveButton").addEventListener("click",playLive);
$("startOverButton").addEventListener("click",()=>playAt(0,"STARTED OVER"));
$("rewindButton").addEventListener("click",()=>{const st=stateAt(),base=mode==="live"?st.elapsedSec:(ytPlayer&&playerReady?ytPlayer.getCurrentTime():manualOffset);playAt(base-30,"REWOUND 30 SEC")});
function safeJSON(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch(_){return fallback}}
function walletProfile(){const session=safeJSON("starquest_session",null),users=safeJSON("starquest_users",{});if(session&&session.key&&users[session.key])return{profile:users[session.key],save:p=>{users[session.key]=p;localStorage.setItem("starquest_users",JSON.stringify(users))}};const guest=safeJSON("starquest_guest_profile_v1",{});return{profile:guest,save:p=>localStorage.setItem("starquest_guest_profile_v1",JSON.stringify(p))}}
function refreshWallet(){const w=walletProfile().profile,tokens=Math.max(0,Number(w.tokens)||0),pending=Math.max(0,Number(w.pendingShareCredits)||0);els.walletAmount.textContent=(tokens+pending/10).toFixed(1)}
function recordShare(){const w=walletProfile(),p=Object.assign({},w.profile),pending=(Number(p.pendingShareCredits)||0)+1;p.shareCount=(Number(p.shareCount)||0)+1;p.pendingShareCredits=pending;while(p.pendingShareCredits>=10){p.pendingShareCredits-=10;p.tokens=(Number(p.tokens)||0)+1}w.save(p);refreshWallet();els.shareStatus.textContent="Share counted · "+p.pendingShareCredits+"/10 toward next ⭐"}
els.share.addEventListener("click",async()=>{const data={title:"Chiller — Classic Suspense Is Already Playing",text:"Vintage suspense is playing live on Chiller.",url:"https://www-infinity4.github.io/Chiller/?card=20260913a"};try{if(navigator.share){await navigator.share(data);recordShare()}else{await navigator.clipboard.writeText(data.url);els.shareStatus.textContent="Link copied — share it to earn credit after a confirmed share."}}catch(err){if(err&&err.name!=="AbortError")els.shareStatus.textContent="Share did not complete."}});
$("walletButton").addEventListener("click",()=>{const w=walletProfile().profile;alert("Chiller wallet\n\nStarCoins: "+(Number(w.tokens)||0)+"\nShare progress: "+(Number(w.pendingShareCredits)||0)+"/10\nConfirmed shares: "+(Number(w.shareCount)||0))});
function tick(){const st=stateAt();updateHeader(st);if(st.key!==lastSlotKey){lastSlotKey=st.key;renderNext(st);if(entered&&mode==="live")playLive();if(new Date().getHours()===0&&new Date().getMinutes()<2)renderGuide()}if(entered&&mode==="live"&&!st.inProgram)showBreak(st);else if(entered&&mode==="live"&&st.inProgram&&els.station.hidden===false)playLive()}
if(!catalog.length){els.title.textContent="No Chiller programs loaded";return}
renderRemote();renderGuide();refreshWallet();tick();setInterval(tick,1000);
})();